### PR TITLE
Proxy-side hostname resolution

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
Currently the driver sets the proxy type to `socks5`, which performs the hostname resolution locally. However, it is also common to let the proxy do the hostname resolution with the `socks5_hostname` proxy type. It's possible to do this by specifying the proxy type in the connection string as `proxyEndpoint=socks5h://proxy_host:port` . This PR updates the connection parameters documentation to reflect that.

### CODE REVIEW

**Comment by nezihyigitbasi** [comment]
We hit this issue on EC2 where we use route 53 cnames to locate our presto cluster. Resolving the hostnames on the client side fails while hostname resolution on the proxy side (with the `socks5h://` scheme) works like a charm.

**Comment by electrum** [comment]
I would change the default. You almost always want the proxy to resolve hostnames. I wasn't aware of this when we added this feature.

**Comment by nezihyigitbasi** [comment]
That's even better. Updated the default to use socks5_hostname proxy type.

**Comment by andralex** [comment]
Thanks!

**Pull request merged**
