### PR TITLE
presto-odbc driver should support numeric functions 

### PR DESCRIPTION
**Pull request by nezihyigitbasi**
-  `SQLGetInfoW` is updated 
  -  handle `SQL_NUMERIC_FUNCTIONS` properly so that user can access Presto's numeric functions.
  - `SQL_AF_DISTINCT` is added to `SQL_AGGREGATE_FUNCTIONS`, which is already supported by Presto
- Nan is handled in the results

It seems like for the numeric functions, the `driver::translateQuery` function is enough to handle odbc escape sequences. Tested with Tableau Desktop v8.2.

### CODE REVIEW

**Comment by markisaa** [comment]
Please separate the NaN handling code into a separate pull request. We would like commits to do one conceptual task. It is also not clear how we can distinguish between the string literal "NaN" and a NaN result from double operations.

I do not believe that we want to enable other functions at this time, even if the `translateQuery` function handles them correctly. Are these functions _absolutely necessary_ to even _look_ at the data you want to look at? Because that is the bar we've used so far to determine what gets added. You may find that if you perform a Tableau data extract that Tableau can perform these operations itself, on locally stored data.

CC: @electrum

**Comment by markisaa** [comment]
Also @electrum - The email you sent me a while back with the translations of ODBC functions to Presto functions seems like something that should be stored somewhere more readily available so that it is not forgotten. The name of the email was "ODBC scalar function escapes", for easy searching.

**Comment by nezihyigitbasi** [comment]
@markisaa I will create a separate PR for NaN handling. One option can be to look at the column metadata in the response to distinguish "NaN" and double Nan.

Yep I know that data extraction can be used. But it would be nice and more convenient for the end user to determine whether he wants to use the live connection mode or the data extract mode. The live connection mode is especially nice for interactive exploration of live data, otherwise the user has to re-extract the data to get the fresh view.

**Comment by markisaa** [comment]
@nezihyigitbasi - Awesome! Please include that check in the new PR.

The decision as to how we proceed regarding functions like this is one that must fall to @electrum. One influencing factor would be the following: Which of the functions can you actually demonstrate that Tableau attempts to use?

**Comment by nezihyigitbasi** [comment]
Actually in live mode the user can use any function that Tableau presents in its UI. When I try to explore the data in live mode Tableau says that many functions are not supported by the driver and recommends extracting the data. Just for reference here are the functions that Tableau complains about:

```
This ODBC driver does not support important capabilities used by Tableau.
This unsupported function is required for relative date filters: The date part named 'day' for the date function: DATETRUNC(date_part, date, [start_of_week])
This unsupported function is required for relative date filters: The date part named 'hour' for the date function: DATETRUNC(date_part, date, [start_of_week])
This unsupported function is required for relative date filters: The date part named 'minute' for the date function: DATETRUNC(date_part, date, [start_of_week])
This unsupported function is required for relative date filters: The date part named 'month' for the date function: DATETRUNC(date_part, date, [start_of_week])
This unsupported function is required for relative date filters: The date part named 'quarter' for the date function: DATETRUNC(date_part, date, [start_of_week])
This unsupported function is required for relative date filters: The date part named 'second' for the date function: DATETRUNC(date_part, date, [start_of_week])
This unsupported function is required for relative date filters: The date part named 'week' for the date function: DATETRUNC(date_part, date, [start_of_week])
-----
Tableau identified the following warnings for the ODBC data source named 'Custom_SQL_Query (hive)':
This aggregation is unsupported: Attribute
This aggregation is unsupported: Count (Distinct)
This aggregation is unsupported: Std. Dev
This aggregation is unsupported: Std. Dev (Pop.)
This aggregation is unsupported: Trunc Day
This aggregation is unsupported: Trunc Hour
This aggregation is unsupported: Trunc Minute
This aggregation is unsupported: Trunc Month
This aggregation is unsupported: Trunc Quarter
This aggregation is unsupported: Trunc Second
This aggregation is unsupported: Trunc Week Number
This aggregation is unsupported: Trunc Year
This aggregation is unsupported: Variance
This aggregation is unsupported: Variance (Pop.)
This function is unsupported: != with parameter types 'date, datetime'
This function is unsupported: != with parameter types 'datetime, date'
This function is unsupported: % with parameter types 'integer, integer'
This function is unsupported: + with parameter types 'string, string'
This function is unsupported: / with parameter types 'integer, integer'
This function is unsupported: < with parameter types 'date, datetime'
This function is unsupported: < with parameter types 'datetime, date'
This function is unsupported: <= with parameter types 'date, datetime'
This function is unsupported: <= with parameter types 'datetime, date'
This function is unsupported: == with parameter types 'date, datetime'
This function is unsupported: == with parameter types 'datetime, date'
This function is unsupported: > with parameter types 'date, datetime'
This function is unsupported: > with parameter types 'datetime, date'
This function is unsupported: >= with parameter types 'date, datetime'
This function is unsupported: >= with parameter types 'datetime, date'
This function is unsupported: ABS(number) with parameter types 'float'
This function is unsupported: ABS(number) with parameter types 'integer'
This function is unsupported: ACOS(number) with parameter types 'float'
This function is unsupported: ASCII(string) with parameter types 'string'
This function is unsupported: ASIN(number) with parameter types 'float'
This function is unsupported: ATAN(number) with parameter types 'float'
This function is unsupported: ATAN2(y number, x number) with parameter types 'float, float'
This function is unsupported: CHAR(integer) with parameter types 'float'
This function is unsupported: CHAR(integer) with parameter types 'integer'
This function is unsupported: CONTAINS with parameter types 'string, string'
This function is unsupported: COS(angle) with parameter types 'float'
This function is unsupported: COT(angle) with parameter types 'float'
This function is unsupported: DATE with parameter types 'date'
This function is unsupported: DATE with parameter types 'datetime'
This function is unsupported: DATE with parameter types 'float'
This function is unsupported: DATE with parameter types 'string'
This function is unsupported: DATEPART_DAYOFYEAR_INTERNAL with parameter types 'date'
This function is unsupported: DATEPART_WEEK_INTERNAL with parameter types 'date'
This function is unsupported: DATETIME with parameter types 'date'
This function is unsupported: DATETIME with parameter types 'datetime'
This function is unsupported: DATETIME with parameter types 'integer'
This function is unsupported: DATETIME with parameter types 'string'
This function is unsupported: DEGREES(number) with parameter types 'float'
This function is unsupported: ENDSWITH with parameter types 'string, string'
This function is unsupported: EXP(number) with parameter types 'float'
This function is unsupported: FIND with parameter types 'string, string, integer'
This function is unsupported: FIND(string, substring, [start]) with parameter types 'string, string'
This function is unsupported: FIND(string, substring, [start]) with parameter types 'string, string, float'
This function is unsupported: FIND(string, substring, [start]) with parameter types 'string, string, integer'
This function is unsupported: FLOAT with parameter types 'float'
This function is unsupported: FLOAT with parameter types 'integer'
This function is unsupported: FLOAT with parameter types 'string'
This function is unsupported: INT with parameter types 'integer'
This function is unsupported: INT with parameter types 'string'
This function is unsupported: LEFT with parameter types 'string, integer'
This function is unsupported: LEFT(string, num_chars) with parameter types 'string, integer'
This function is unsupported: LEFT_INTERNAL with parameter types 'string, integer'
This function is unsupported: LEN(string) with parameter types 'string'
This function is unsupported: LN with parameter types 'float'
This function is unsupported: LN(number) with parameter types 'float'
This function is unsupported: LOG with parameter types 'float'
This function is unsupported: LOG(number, [base]) with parameter types 'float'
This function is unsupported: LOWER(string) with parameter types 'string'
This function is unsupported: LTRIM(string) with parameter types 'string'
This function is unsupported: MID with parameter types 'string, integer'
This function is unsupported: MID with parameter types 'string, integer, integer'
This function is unsupported: MID(string,start,[length]) with parameter types 'string, float'
This function is unsupported: MID(string,start,[length]) with parameter types 'string, float, float'
This function is unsupported: MID(string,start,[length]) with parameter types 'string, integer'
This function is unsupported: MID(string,start,[length]) with parameter types 'string, integer, integer'
This function is unsupported: MID_INTERNAL with parameter types 'string, integer'
This function is unsupported: NOW()
This function is unsupported: PI()
This function is unsupported: POWER with parameter types 'float, integer'
This function is unsupported: POWER(number,power) with parameter types 'float, integer'
This function is unsupported: POWER(number,power) with parameter types 'integer, integer'
This function is unsupported: RADIANS(number) with parameter types 'float'
This function is unsupported: RIGHT with parameter types 'string, integer'
This function is unsupported: RIGHT(string, num_chars) with parameter types 'string, integer'
This function is unsupported: RIGHT_INTERNAL with parameter types 'string, integer'
This function is unsupported: ROUND(number, [decimals]) with parameter types 'float'
This function is unsupported: ROUND(number, [decimals]) with parameter types 'float, integer'
This function is unsupported: RTRIM(string) with parameter types 'string'
This function is unsupported: SIGN(number) with parameter types 'float'
This function is unsupported: SIN(angle) with parameter types 'float'
This function is unsupported: SPACE(number) with parameter types 'integer'
This function is unsupported: SQRT(number) with parameter types 'float'
This function is unsupported: STARTSWITH with parameter types 'string, string'
This function is unsupported: STR with parameter types 'date'
This function is unsupported: STR with parameter types 'datetime'
This function is unsupported: STR with parameter types 'float'
This function is unsupported: STR with parameter types 'integer'
This function is unsupported: STR with parameter types 'string'
This function is unsupported: TAN(angle) with parameter types 'float'
This function is unsupported: TODAY()
This function is unsupported: TRIM(string) with parameter types 'string'
This function is unsupported: The date part named 'day' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'dayofyear' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'dayofyear' for the date function: DATEPART(date_part, date, [start_of_week])
This function is unsupported: The date part named 'dayofyear' for the date function: DATEPART(date_part, date, [start_of_week])
This function is unsupported: The date part named 'hour' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'minute' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'month' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'quarter' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'second' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'week' for the date function: DATEDIFF(date_part, start_date, end_date, [start_of_week])
This function is unsupported: The date part named 'week' for the date function: DATEDIFF(date_part, start_date, end_date, [start_of_week])
This function is unsupported: The date part named 'week' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'week' for the date function: DATEPART(date_part, date, [start_of_week])
This function is unsupported: The date part named 'week' for the date function: DATEPART(date_part, date, [start_of_week])
This function is unsupported: The date part named 'weekday' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: The date part named 'weekday' for the date function: DATEPART(date_part, date, [start_of_week])
This function is unsupported: The date part named 'weekday' for the date function: DATEPART(date_part, date, [start_of_week])
This function is unsupported: The date part named 'year' for the date function: DATENAME(date_part, date, [start_of_week])
This function is unsupported: UPPER(string) with parameter types 'string'
```

**Comment by andralex** [comment]
@nezihyigitbasi please rebase or close. Thanks!

**Comment by nezihyigitbasi** [comment]
Closing this one for now as our internal users seem to be OK with using the extract mode only. If we get a request for live mode in the future, we can have another look at this. Thanks @andralex

**Pull request closed without merging**
